[theme]
base                     = "light"
primaryColor             = "#1B365D"   # Goldman navy
backgroundColor          = "#FAFAF7"   # off-white quente (page)
secondaryBackgroundColor = "#EFEAE0"   # marfim escuro (sidebar)
textColor                = "#1A1A1A"
font                     = "serif"

[server]
headless = true

[browser]
gatherUsageStats = false
